// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanoEnsinoAPI.Data;

namespace PlanoEnsinoAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211130085308_InitialFull")]
    partial class InitialFull
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PlanoEnsinoAPI.Models.Autor", b =>
                {
                    b.Property<int>("CdAutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CdAutor");

                    b.ToTable("Autor");
                });

            modelBuilder.Entity("PlanoEnsinoAPI.Models.Curso", b =>
                {
                    b.Property<int>("CdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DsCurso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TpGraduacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CdCurso");

                    b.ToTable("Curso");
                });

            modelBuilder.Entity("PlanoEnsinoAPI.Models.CursoPlanoEnsino", b =>
                {
                    b.Property<int>("CdCurso")
                        .HasColumnType("int");

                    b.Property<int>("CdDisciplina")
                        .HasColumnType("int");

                    b.Property<int>("CdCursoPlanoEnsino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("CdCurso", "CdDisciplina");

                    b.HasIndex("CdDisciplina");

                    b.ToTable("CursoPlanoEnsino");
                });

            modelBuilder.Entity("PlanoEnsinoAPI.Models.Livro", b =>
                {
                    b.Property<int>("CdLivro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("DsLivro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Editora")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CdLivro");

                    b.ToTable("Livro");
                });

            modelBuilder.Entity("PlanoEnsinoAPI.Models.LivroAutor", b =>
                {
                    b.Property<int>("CdLivro")
                        .HasColumnType("int");

                    b.Property<int>("CdAutor")
                        .HasColumnType("int");

                    b.Property<int>("CdLivroAutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("CdLivro", "CdAutor");

                    b.HasIndex("CdAutor");

                    b.ToTable("LivroAutor");
                });

            modelBuilder.Entity("PlanoEnsinoAPI.Models.LivroPlanoEnsino", b =>
                {
                    b.Property<int>("CdLivro")
                        .HasColumnType("int");

                    b.Property<int>("CdDisciplina")
                        .HasColumnType("int");

                    b.Property<int>("CdLivroPlanoEnsino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TpBibliografia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CdLivro", "CdDisciplina");

                    b.HasIndex("CdDisciplina");

                    b.ToTable("LivroPlanoEnsino");
                });

            modelBuilder.Entity("PlanoEnsinoAPI.Models.PlanoEnsino", b =>
                {
                    b.Property<int>("CdDisciplina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnoSemestre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsAlunoA1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsAlunoA2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsAlunoA3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsAlunoA4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsAvaliacaoA1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsAvaliacaoA2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsAvaliacaoA3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsAvaliacaoA4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsConsultaA1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsConsultaA2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsConsultaA3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsConsultaA4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsConteudoA1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsConteudoA2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsConteudoA3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsConteudoA4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsDisciplina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsEmenta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsMTDGeral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsObjetivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsObservacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsObservacaoA1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsObservacaoA2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsObservacaoA3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsObservacaoA4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsSemana1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsSemana10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsSemana11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsSemana12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsSemana13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsSemana14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsSemana15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsSemana16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsSemana17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsSemana18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsSemana19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsSemana2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsSemana20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsSemana3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsSemana4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsSemana5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsSemana6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsSemana7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsSemana8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsSemana9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DtAtualização")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("NomeA1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeA2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeA3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeA4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NrCreditos")
                        .HasColumnType("int");

                    b.Property<int>("NrHorasPP")
                        .HasColumnType("int");

                    b.Property<int>("NrHorasSala")
                        .HasColumnType("int");

                    b.Property<string>("PesoA1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesoA2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesoA3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesoA4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CdDisciplina");

                    b.ToTable("PlanoEnsino");
                });

            modelBuilder.Entity("PlanoEnsinoAPI.Models.SugestaoPlanoEnsino", b =>
                {
                    b.Property<int>("CdSugestaoPlanoEnsino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CdDisciplina")
                        .HasColumnType("int");

                    b.Property<string>("DsExclusaoBasica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsExclusaoComplementar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsInclusaoBasica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsInclusaoComplementar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsSugestaoPlanoEnsino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DtCadastroSugestao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int?>("PlanoEnsinoCdDisciplina")
                        .HasColumnType("int");

                    b.HasKey("CdSugestaoPlanoEnsino");

                    b.HasIndex("PlanoEnsinoCdDisciplina");

                    b.ToTable("SugestaoPlanoEnsino");
                });

            modelBuilder.Entity("PlanoEnsinoAPI.Models.Usuario", b =>
                {
                    b.Property<int>("CdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TpUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("PlanoEnsinoAPI.Models.UsuarioPlanoEnsino", b =>
                {
                    b.Property<int>("CdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("CdDisciplina")
                        .HasColumnType("int");

                    b.Property<int>("CdUsuarioPlanoEnsino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("CdUsuario", "CdDisciplina");

                    b.HasIndex("CdDisciplina");

                    b.ToTable("UsuarioPlanoEnsino");
                });

            modelBuilder.Entity("PlanoEnsinoAPI.Models.CursoPlanoEnsino", b =>
                {
                    b.HasOne("PlanoEnsinoAPI.Models.Curso", "Curso")
                        .WithMany("cursoPlanoEnsinos")
                        .HasForeignKey("CdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanoEnsinoAPI.Models.PlanoEnsino", "PlanoEnsino")
                        .WithMany("CursoPlanoEnsinos")
                        .HasForeignKey("CdDisciplina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlanoEnsinoAPI.Models.LivroAutor", b =>
                {
                    b.HasOne("PlanoEnsinoAPI.Models.Autor", "Autor")
                        .WithMany("AutoresLivros")
                        .HasForeignKey("CdAutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanoEnsinoAPI.Models.Livro", "Livro")
                        .WithMany("LivroAutores")
                        .HasForeignKey("CdLivro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlanoEnsinoAPI.Models.LivroPlanoEnsino", b =>
                {
                    b.HasOne("PlanoEnsinoAPI.Models.PlanoEnsino", "PlanoEnsino")
                        .WithMany("LivroPlanos")
                        .HasForeignKey("CdDisciplina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanoEnsinoAPI.Models.Livro", "Livro")
                        .WithMany("LivroPlanos")
                        .HasForeignKey("CdLivro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlanoEnsinoAPI.Models.SugestaoPlanoEnsino", b =>
                {
                    b.HasOne("PlanoEnsinoAPI.Models.PlanoEnsino", "PlanoEnsino")
                        .WithMany("SugestaoPlanos")
                        .HasForeignKey("PlanoEnsinoCdDisciplina");
                });

            modelBuilder.Entity("PlanoEnsinoAPI.Models.UsuarioPlanoEnsino", b =>
                {
                    b.HasOne("PlanoEnsinoAPI.Models.PlanoEnsino", "PlanoEnsino")
                        .WithMany("UsuarioPlanoEnsinos")
                        .HasForeignKey("CdDisciplina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanoEnsinoAPI.Models.Usuario", "Usuario")
                        .WithMany("UsuarioPlanoEnsinos")
                        .HasForeignKey("CdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
